name: Atividade Somativa 2 - DevOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: wbotta/appsomativa2:latest

      - name: Mensagem final
        run: echo 'Etapa concluída com sucesso!'

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: wbotta/appsomativa2:latest
      - name: Run SAST test
        uses: shiftleftsecurity/sast-scan@v2.1.1
        with:
          language: javascript
          scan-path: .
          fail-on-error: true
          
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Finalizado!"
