name: Atividade Somativa 2 - DevOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Build
        run: echo 'Etapa concluída com sucesso!'

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Template de Segurança SAST
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Análise de segurança SAST
        uses: github/codeql-action/analyze@v2
        with:
          query: javascript-code-scanning.qls
          languages: javascript

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Finalizado!"
