name: Atividade Somativa 2 - DevOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t appwebsomativa2 .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t appwebsomativa2 .

      - name: Run SAST test
        uses: shiftleftsecurity/sast-scan@v2.1.1
        with:
          language: html, javascript
          scan-path: .
          fail-on-error: true
          
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Finalizado!"
