name: Atividade Somativa 2 - DevOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t appwebsomativa2 .

      - name: Push Docker image
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker tag appwebsomativa2 wbotta/appwebsomativa2
      - run: docker push wbotta/appwebsomativa2

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t appwebsomativa2 .

      - name: Run tests
        run: docker run --rm appwebsomativa2 npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t somativa2 .
      - name: Deploy to production
        run: |
          docker tag somativa2 your-docker-username/somativa2
          docker push your-docker-username/somativa2
          ssh user@your-server-ip "docker pull your-docker-username/somativa2 && docker run -d -p 80:80 --name somativa2 your-docker-username/somativa2"
