name: Atividade Somativa 2 - DevOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build
        run: echo 'Etapa concluída com sucesso!'

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instala o template de segurança SAST via CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: html, javascript

      - name: Executa a análise de segurança SAST via CodeQL
        uses: github/codeql-action/analyze@v2
        with:
          language: javascript

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Finalizado!"
