name: Atividade Somativa 2 - DevOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: echo 'Etapa concluída com sucesso!'

  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalação de dependências
        run: npm install
      - name: Run SAST test
        uses: shiftleftsecurity/sast-scan@v2.1.1
        with:
          language: javascript
          scan-path: .
          fail-on-error: true

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in no DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t myimage .

      - name: Push Docker image
        run: docker push myimage

      - name: Enviar notificação
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"content": "Uma nova imagem Docker foi publicada!"}' \
            $DISCORD_WEBHOOK
